# -*- coding: utf-8 -*-
"""SkillsUpdated.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xVWGSPAW39HLv1Kuuvr2HBxH14Z1DxpG

# Welcome to Colab!
"""

!pip install spacy PyPDF2
!python -m spacy download en_core_web_sm

import spacy
import PyPDF2


def extract_text_from_pdf(pdf_path):
    text = ""
    try:

        with open(pdf_path, 'rb') as file:
            reader = PyPDF2.PdfReader(file)

            for page in reader.pages:
                text += page.extract_text() + " "
    except Exception as e:
        return f"Error reading PDF: {e}"
    return text

# 2. LOAD SPACY MODEL
nlp = spacy.load("en_core_web_sm")

# 3. YOUR ORIGINAL LOGIC
def extract_skills(text):
    doc = nlp(text)
    skills = set()
    for token in doc:
        if token.pos_ == "NOUN":
            skills.add(token.text.lower())
    return skills

def skill_gap_analysis(pdf, job_desc):

    resume_text = extract_text_from_pdf(pdf)

    resume_skills = extract_skills(resume_text)
    job_skills = extract_skills(job_desc)

    missing_skills = job_skills - resume_skills

    return {
        "Resume Skills": list(resume_skills),
        "Required Skills": list(job_skills),
        "Missing Skills": list(missing_skills)
    }


# Create a dummy file to test the code so it doesn't fail on "File not found"
with open("test_resume.pdf", "w") as f:
    f.write("dummy pdf content")
# Note: The above creates a corrupted dummy PDF just to satisfy the file path check.
# For real results, upload a real PDF named "test_resume.pdf" to your notebook files.

print("Code is ready to run!")
